package io.github.florentclarret.dailycodingpuzzles.month1;

/**
 * Even Fibonacci Numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * Find the sum of the even-valued terms.
 */
public final class Day1 {

    public static int evenFibonacciNumbers(int n) {
        int sum, firstValue = 0, secondValue = 1, result = 0;

        while (n > 0) {
            sum = firstValue + secondValue;
            firstValue = secondValue;
            secondValue = sum;

            if (sum % 2 == 0) {
                result = result + sum;
            }

            --n;
        }

        return result;
    }
}
